FROM maven:3.9.9-eclipse-temurin-22-jammy as builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src/ ./src/

RUN mvn clean package -DskipTests=true

# setup the application

FROM amazoncorretto:22-alpine as prod

RUN mkdir /app

COPY --from=builder /app/target/*.jar /app/application.jar

ENV SERVER_PORT=8181

WORKDIR /app

EXPOSE 8181

ENTRYPOINT ["java", "-Xmx2048M", "-jar", "application.jar"]


# this works with pre build jar file
# FROM amazoncorretto:22-alpine

# ARG JAR_FILE=target/*.jar

# COPY ${JAR_FILE} application.jar

# CMD apt-get update -y

# ENTRYPOINT ["java", "-Xmx2048M", "-jar", "/application.jar"]